spring:
  application:
    name: zuul-server

server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka}
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

zuul:
  routes:
    greeting:
      path: /gservice/**
      serviceId: eureka-client
      
      